### ISSUE TITLE
When use Curl::post i get HTTP/1.1 400 Content Length Required 

### ISSUE THREAD

**Issue by rkmax** [php-curl-class/php-curl-class#123]

**Comment by zborboa-google** [comment]
Hi @rkmax. Can you provide an example to reproduce? Thank you

**Comment by zachborboa** [comment]
The server you are POSTing to may be running an older version of Apache Traffic Server. The response is unique in that a `400 Content Length Required` isn't actually a valid HTTP response. It probably meant `411 Length Required` even though `Content-Length` isn't required for POST requests. This issue has been fixed in more recent versions of Apache Traffic Server (https://github.com/apache/trafficserver/commit/db3de18 / [Allow POST requests without a Content-Length header](https://github.com/apache/trafficserver/commit/db3de18)).

A couple options:
- Update the server
- Specify a Content-Length header

**Comment by zachborboa** [comment]
Referenced
https://issues.apache.org/jira/browse/TS-2902
