### ISSUE TITLE
File Upload w/o CURLFile Class in PHP Version < 5.5.0 don´t work

### ISSUE THREAD

**Issue by aisn** [php-curl-class/php-curl-class#323]
If the CURLFile Class doesn´t exists, the class_exists call in Curl::buildPostData (Line: 155) produce a  fatal error, cause of the missing 2nd parameter "autoload".

**Comment by thebeline** [comment]
Can you please provide the full text of the fatal error?

**Comment by aisn** [comment]
Additionaly i can narrow down the issue causes an error only for using a custom autoloader.
Disable the autoload in class_exists call is required in my case. 

My error log isn´t representative, i use Prado Framwork...
> 2016-04-06 15:30:45 Error handler:include_once(CURLFile.php): failed to open stream: No such file or directory, Zeile: 101 in Datei: D:\Zend\Apache2\htdocs\jobportal\framework\PradoBase.php,

**Comment by thebeline** [comment]
It is important to note that `include` does not fatal if the directory/file is not found, it simply returns false, so `include_once(CURLFile.php): failed to open stream` is not what is fataling your application.

This is an issue with `PradoBase.php`, and not with this library.  As you can see, looking at the `PradoBase.php` source [here](https://github.com/pradosoft/prado/blob/master/framework/PradoBase.php#L105), Prado is creating the fatal.  Auto-loaders should *not* throw exceptions or fatal errors, and should let PHP handle the resulting errors internally, otherwise, functions like `class_exists` (which you would not know if the class exists unless you load it) are no longer useful.  It defeats the purpose of the function, which is to conditionalize behavior on the existence of a class, and to auto load it if it can, not fatal the application.  FURTHER, auto-loaders should be able to stack, with one auto-loader attempting to load a class, and returning `true` or `false` and passing the attempt down the line.  Fataling the application breaks this behavior.  This is unacceptable.

This is not an issue with this library, and you should submit a ticket outlining the issue to the Prado repository.  That behavior breaks more things about PHP and class loading than I can list.

**Comment by thebeline** [comment]
Made a [ticket ](https://github.com/pradosoft/prado/issues/582 )for you.

**Comment by aisn** [comment]
Thanks for your effort. 

I still think there´s generally no need to possibly invoke a autoloader function to load PHP supported libcurl Library Class CURLFile (PHP 5 >= 5.5.0, PHP 7) [here](https://github.com/php-curl-class/php-curl-class/blob/master/src/Curl/Curl.php#L155).

**Comment by thebeline** [comment]
Unless I am missing something, that is what `class_exists` and auto-loaders are for.  You want to instantiate a class, but you use `class_exists` to see if you can so you do not fatal the application.  Using `class_exists` should not fatal the application on it's own.  Many frameworks do not implicitly load any class definitions, save for the auto-loaders, at all.

There are two options:
1. Expect it exists, is loaded, or can be loaded, and simply instantiate it `$obj = new Class` - This will fatal for people who do not have the class.
2. Check without auto-loading - This will disable it for anyone who relies on auto-loaders.

As the documented, default, and expected behavior for `class_exists` is to attempt to auto-load the class, I don't see why we should change the behavior.  

However, ultimately, it is up to @zachborboa, I guess.

**Comment by thebeline** [comment]
@aisn Sometimes it pays to be the squeeky wheel.  This will be resolved in Prado 3.3.1 in a few days.

https://github.com/pradosoft/prado/pull/583

**Comment by zachborboa** [comment]
@aisn Has this issue been resolved?

For php < 5.5.0 when CURLFile class doesn't exists, the library will use the old @filename file uploading.

**Comment by zachborboa** [comment]
Closing as this seems to no longer be an issue. Please comment if the issue persists. Thanks
