### ISSUE TITLE
GET method timeout after use PUT method

### ISSUE THREAD

**Issue by walangkaji** [php-curl-class/php-curl-class#472]
I've request put and then get request:

```
$curl->put('https://httpbin.org/put', array(
    'id' => '1',
    'first_name' => 'Zach',
    'last_name' => 'Borboa',
));
if ($curl->error) {
    echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
} else {
    echo 'Data server received via PUT:' . "\n";
    var_dump($curl->response->form);
}

$curl->get('https://httpbin.org/get', array(
    'key' => 'value',
));
if ($curl->error) {
    echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
} else {
    echo 'Response:' . "\n";
    var_dump($curl->response);
}
```

Error: 28: Timeout was reached: Operation timed out after 30000 milliseconds with 0 bytes received

how can I run this method?

**Comment by sganz** [comment]
Not sure if this is the same thing I'm running into. I am doing a PUT and after I do no subsequent POST operations will work due to time out. I looked at some of the dumps from CURL directly (use verbose()) and seems like the content-length header might be carrying over from the last PUT operation, but it's never set (Or I don't think it is) for the POST. Going to try to manually set it and see if it helps.

**Comment by sganz** [comment]
Ok, I fixed it in my case but setting the content-length correctly. I'm not sure if this applies to the get call but it fixed my issue. I'm going to open a new issue for it.

**Comment by walangkaji** [comment]
@sganz yap, i think the problem in content-length,
I've just insert this opt after PUT method:

`$curl->removeHeader('Content-Length');`

**Comment by zachborboa** [comment]
Hi. Thanks for reporting the issue and the code to reproduce. The issue should now be fixed.

**Comment by sganz** [comment]
I'll pull a new version and give it a test. Hopefully that will fix the issue on the post as well. Thanks for the quick reply!

Sandy
